{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vesmaro-eyes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vesmaro-eyes.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
