/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly "/kora/sessions": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Session list across all connected hosts (slice 1).
     * @description Derived-registry listing: every session discovered by host scanners
     *     across enrolled executors (zcode/vscode/pi; hermes is a known gap
     *     until T004). Presence ≠ liveness: the two-hour presence discipline
     *     lives on executors; `state` here reflects the session, not the host.
     *
     *     `last_line_preview` is clamped to 160 characters and passes the
     *     single redaction choke-point (x-kora-redaction) — previews are the
     *     same serving path as transcripts, gated from slice 1.
     *
     *     Response also carries the coverage block powering the «что вижу /
     *     чего нет» screen — the honest per-harness visibility statement.
     */
    readonly get: operations["listKoraSessions"];
    readonly put?: never;
    /**
     * Start a NEW session from the phone (slice 3, first relay scenario).
     * @description Spawns a headless harness on the store-owner host via the relay
     *     (`--resume` continuation is the SECOND scenario; this route always
     *     starts fresh). The created session is relay-origin by construction —
     *     provenance gates do not apply to it, it is steerable from birth.
     *
     *     Requires an active step-up PIN (403 `step_up_required` otherwise).
     *     The initial prompt rides the same in-memory relay queue with honest
     *     delivery semantics as message sends.
     */
    readonly post: operations["createKoraSession"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/kora/sessions/{session_id}/transcript": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Read-only transcript tail by seq cursor (slice 2).
     * @description The ONE transcript-serving path (chat v1 reads the same route):
     *     authenticated GET, `after_seq` cursor, per-page limit. Items are
     *     ordered by `seq` ascending; `seq` is assigned by the harness store
     *     order (per-session, monotonically increasing) and is never
     *     renumbered.
     *
     *     Every response re-validates the session (registry lookup) and every
     *     content field passes the redaction choke-point. Each call emits the
     *     `session.transcript_viewed` audit record (device class / network
     *     path / session host) — full reads and live tails alike.
     *
     *     mnd_ class: 403 with an explanatory body (the wall explains why
     *     transcripts are forbidden and what to do instead) — never a bare 403.
     */
    readonly get: operations["getKoraSessionTranscript"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/kora/sessions/{session_id}/messages": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Send a prompt into a session via the relay (slice 3).
     * @description A relay COMMAND, not a store write: the relay unit-process queues
     *     the prompt in-memory and the harness itself appends to its store
     *     (NO-DRIFT). The browser then observes the effect by re-reading the
     *     transcript tail (`session.updated` is the dictionary signal).
     *
     *     Provenance gate: only relay-origin or adopted (typed-confirm)
     *     sessions are steerable; a foreign triple resolves as 404
     *     (`session_not_found`), enforced server-side — never hidden in the UI.
     *     Steering requires the step-up PIN to be active; otherwise 403 with
     *     code `step_up_required`.
     *
     *     Delivery is honest: the relay queue is in-memory, a failed delivery
     *     is reported as `failed` (retryable) with the «не доставлено —
     *     повторите» semantics — nothing is silently dropped or spurged.
     *     Confirm-mode is the default; `confirm_required=false` only for
     *     sessions explicitly opted into yolo (audited).
     */
    readonly post: operations["sendKoraSessionMessage"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/kora/steering/step-up": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /** Step-up status (active / remaining TTL). */
    readonly get: operations["getKoraSteeringStepUpStatus"];
    readonly put?: never;
    /**
     * Enable steering with the step-up PIN (slice 3).
     * @description Unlocks steering (message sends + new relay sessions) for the
     *     owner-session cookie. TTL ≤ 15 minutes, sliding per grant; steering
     *     is OFF by default — reading never requires step-up. The PIN value is
     *     never logged (hash + length only, same hygiene as prompt logging).
     */
    readonly post: operations["enableKoraSteeringStepUp"];
    /**
     * Revoke the step-up grant immediately.
     * @description The one-command kill switch for the steering window.
     */
    readonly delete: operations["revokeKoraSteeringStepUp"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Harness families wired in phase 1. hermes is a KNOWN GAP until T004 (absent from the enum by design; the coverage block says so loudly).
     * @enum {string}
     */
    readonly KoraHarness: "zcode" | "vscode" | "pi";
    /**
     * @description Session liveness (presence ≠ liveness — executor presence is a separate concept). `dead` = the process was marked dead (recovery semantics): the SESSION stays in the registry and remains visible; relay sessions survive executor restarts.
     * @enum {string}
     */
    readonly KoraSessionState: "live" | "idle" | "dead";
    /**
     * @description `relay` = born via the Kora relay (steerable from birth); `local` = started outside Kora (steerable only after typed-confirm adoption).
     * @enum {string}
     */
    readonly KoraOrigin: "relay" | "local";
    /** @description One session row of the derived registry (PK fields exposed). */
    readonly KoraSessionOut: {
      /** @description Opaque board-side handle (see KoraSessionId). */
      readonly id: string;
      /** @description Enrolled executor owning the host store (registry PK part 1). */
      readonly executor_id: string;
      /** @description Harness-native session id inside that store (registry PK part 2). */
      readonly native_id: string;
      readonly harness: components["schemas"]["KoraHarness"];
      /** @description Project name as the harness reports it (null when unknown). */
      readonly project?: string | null;
      /** @description Working directory of the session (null when unknown). */
      readonly cwd?: string | null;
      readonly state: components["schemas"]["KoraSessionState"];
      readonly origin: components["schemas"]["KoraOrigin"];
      /** @description Server-computed: relay origin OR adopted via typed-confirm. The UI renders the honest «чужая сессия — только чтение» plate when false; the send path still enforces it server-side. */
      readonly steerable: boolean;
      /**
       * Format: date-time
       * @description Session start (RFC 3339; null when the harness lacks it).
       */
      readonly started_at?: string | null;
      /**
       * Format: date-time
       * @description Last store activity (RFC 3339; null when unknown).
       */
      readonly last_activity_at?: string | null;
      /**
       * Format: int64
       * @description Age snapshot at listing time (derived from started_at).
       */
      readonly age_seconds: number;
      /** @description Clamped last-line preview — ≤ 160 chars, then redacted by the single choke-point (x-kora-redaction). Nullable. */
      readonly last_line_preview?: string | null;
    };
    readonly KoraCoverageHarness: {
      /** @description Harness family (may name families outside the enum, e.g. hermes). */
      readonly harness: string;
      /**
       * @description Visibility level: `full` = lists + transcripts; `lists-only` = metadata + previews (vscode in slice 2: full transcript is a known gap, kind:1); `metadata-only`; `absent` = not scanned (hermes until T004).
       * @enum {string}
       */
      readonly support: "full" | "lists-only" | "metadata-only" | "absent";
      /** @description Human explanation of the support level (shown on the coverage screen). */
      readonly note?: string | null;
    };
    /** @description Data for the «что вижу / чего нет» screen: the honest per-harness visibility statement plus explicit gaps. Rendered from slice 1. */
    readonly KoraCoverageOut: {
      readonly harnesses: readonly components["schemas"]["KoraCoverageHarness"][];
      /** @description Explicit gap strings (e.g. remote hosts pending the W4 loopback-ingress schedule; hermes → T004; vscode full transcripts kind:1). Honest visibility, no silent holes. */
      readonly gaps: readonly string[];
    };
    readonly KoraSessionsOut: {
      /** @enum {boolean} */
      readonly ok: true;
      readonly count: number;
      readonly items: readonly components["schemas"]["KoraSessionOut"][];
      readonly coverage: components["schemas"]["KoraCoverageOut"];
      readonly meta: {
        /** Format: date-time */
        readonly generated_at: string;
      };
    };
    /** @description One transcript entry, content redacted by the choke-point. */
    readonly KoraTranscriptItemOut: {
      /**
       * Format: int64
       * @description Per-session monotonic cursor position (harness store order).
       */
      readonly seq: number;
      /** @enum {string} */
      readonly role: "user" | "assistant" | "system" | "tool";
      /** @description Optional harness-specific entry kind (e.g. vscode kind tag). */
      readonly kind?: string | null;
      /**
       * Format: date-time
       * @description Entry timestamp (null when the harness lacks it).
       */
      readonly ts: string | null;
      /** @description Redacted entry body (single choke-point — see x-kora-redaction). */
      readonly content: string;
      /** @description Honest signal that the choke-point masked something in this entry. */
      readonly redaction_applied: boolean;
    };
    readonly KoraTranscriptOut: {
      readonly session_id: string;
      readonly items: readonly components["schemas"]["KoraTranscriptItemOut"][];
      /**
       * Format: int64
       * @description Cursor for the next page (last returned seq; unchanged from the request's after_seq when the page is empty).
       */
      readonly next_after_seq: number;
      /** @description More items exist beyond this page (same cursor path). */
      readonly has_more: boolean;
    };
    /** @description Honest relay delivery state. The queue is in-memory by design (rev.2 #3); `failed` is retryable and rendered as «не доставлено — повторите», never silently dropped. */
    readonly KoraDeliveryOut: {
      /** @enum {string} */
      readonly status: "queued" | "delivered" | "failed";
      /** Format: date-time */
      readonly queued_at?: string | null;
      /** Format: date-time */
      readonly delivered_at?: string | null;
      /** @description True when a retry makes sense (default true for failed). */
      readonly retryable?: boolean;
      /** @description Human-readable failure reason (no secrets, no raw prompt). */
      readonly error?: string | null;
    };
    /** @description New relay session from the phone (executor + project + prompt). */
    readonly KoraSessionCreate: {
      /** @description Enrolled executor to spawn the headless harness on. */
      readonly executor_id: string;
      /** @description Project to open the session in. */
      readonly project: string;
      /** @description Initial prompt. Transported stdin/JSON or app-server — NEVER argv (leaks into /proc/*\/cmdline). Logs carry hash + length only. */
      readonly prompt: string;
    };
    readonly KoraSessionCreatedOut: {
      /** @enum {boolean} */
      readonly ok: true;
      readonly session: components["schemas"]["KoraSessionOut"];
      readonly delivery: components["schemas"]["KoraDeliveryOut"];
    };
    readonly KoraMessageCreate: {
      /** @description Prompt text (same transport + logging hygiene as the initial prompt). */
      readonly text: string;
    };
    readonly KoraMessageAcceptedOut: {
      /** @enum {boolean} */
      readonly ok: true;
      readonly session_id: string;
      readonly delivery: components["schemas"]["KoraDeliveryOut"];
      /** @description True in the default confirm-mode (the relay confirms host-side before the harness runs). False ONLY for sessions explicitly opted into yolo (audited, never default). */
      readonly confirm_required: boolean;
    };
    readonly KoraStepUpIn: {
      /** @description Step-up PIN. Never logged (hash + length only). */
      readonly pin: string;
    };
    readonly KoraStepUpOut: {
      /** @enum {boolean} */
      readonly ok: true;
      /** Format: date-time */
      readonly granted_until: string;
      /** @description Grant window — ≤ 900s (15 min) by contract. */
      readonly ttl_seconds: number;
    };
    readonly KoraStepUpStatusOut: {
      readonly active: boolean;
      /** Format: date-time */
      readonly granted_until?: string | null;
      readonly ttl_remaining_seconds?: number | null;
    };
    /** @description Honest error body. The mnd_ wall carries an EXPLANATION (why transcripts are forbidden and what to do), not a bare status. */
    readonly KoraErrorOut: {
      /** @enum {boolean} */
      readonly ok: false;
      /** @enum {string} */
      readonly code:
        | "unauthorized"
        | "metadata_only"
        | "step_up_required"
        | "step_up_denied"
        | "session_not_found"
        | "host_conflict"
        | "validation";
      /** @description Human-readable explanation (RU-first UI copy source). */
      readonly message: string;
    };
    /** @description A scanner discovered a session new to the registry. METADATA ONLY — no preview text, no content (vocabulary is additive-only). */
    readonly KoraSessionListedEvent: {
      /** @enum {string} */
      readonly event: "session.listed";
      readonly session_id: string;
      readonly executor_id: string;
      readonly native_id: string;
      readonly harness: components["schemas"]["KoraHarness"];
      readonly project?: string | null;
      /** Format: date-time */
      readonly at: string;
    };
    /** @description The session store changed (accepted only from the executor owning the session — ingest binding, security gate 1). This is the chat-v1 SIGNAL: the browser pulls the tail via the authenticated transcript GET. METADATA ONLY — never content. */
    readonly KoraSessionUpdatedEvent: {
      /** @enum {string} */
      readonly event: "session.updated";
      readonly session_id: string;
      /**
       * Format: int64
       * @description Latest known seq (a hint for the cursor; the GET is authoritative).
       */
      readonly last_seq?: number | null;
      /** Format: date-time */
      readonly at: string;
    };
    /** @description Session ended (process exit / registry close-out). METADATA ONLY. */
    readonly KoraSessionClosedEvent: {
      /** @enum {string} */
      readonly event: "session.closed";
      readonly session_id: string;
      /** Format: date-time */
      readonly at: string;
    };
  };
  responses: {
    /** @description No owner session / device token (code `unauthorized`). */
    readonly KoraUnauthorized: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["KoraErrorOut"];
      };
    };
  };
  parameters: {
    /** @description Opaque board-side session handle. Derived from the registry PK (executor_id, native_id); clients treat it as opaque and stable across listings. Not a harness store id. */
    readonly KoraSessionId: string;
    /** @description Filter by harness family. */
    readonly KoraHarnessFilter: components["schemas"]["KoraHarness"];
    /** @description Filter by session state. */
    readonly KoraStateFilter: components["schemas"]["KoraSessionState"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  readonly listKoraSessions: {
    readonly parameters: {
      readonly query?: {
        /** @description Filter by harness family. */
        readonly harness?: components["parameters"]["KoraHarnessFilter"];
        /** @description Filter by session state. */
        readonly state?: components["parameters"]["KoraStateFilter"];
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Listing with coverage. Available to both access classes. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraSessionsOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
    };
  };
  readonly createKoraSession: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["KoraSessionCreate"];
      };
    };
    readonly responses: {
      /** @description Session registered (relay origin) with delivery state. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraSessionCreatedOut"];
        };
      };
      /** @description Validation (code `validation`). */
      readonly 400: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
      /** @description Step-up required (code `step_up_required`) or mnd_ wall (code `metadata_only`). */
      readonly 403: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
      /** @description Host conflict (code `host_conflict`). */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
    };
  };
  readonly getKoraSessionTranscript: {
    readonly parameters: {
      readonly query?: {
        /** @description Return items with seq strictly greater than this cursor. 0 (default) starts from the beginning of the session. */
        readonly after_seq?: number;
        /** @description Page size cap (server clamps to the maximum). */
        readonly limit?: number;
      };
      readonly header?: never;
      readonly path: {
        /** @description Opaque board-side session handle. Derived from the registry PK (executor_id, native_id); clients treat it as opaque and stable across listings. Not a harness store id. */
        readonly session_id: components["parameters"]["KoraSessionId"];
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Transcript page. Content is redacted via the choke-point. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraTranscriptOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
      /** @description mnd_ metadata-only wall (code `metadata_only`) — body carries the explanation, not just the status. */
      readonly 403: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
      /** @description Unknown session (code `session_not_found`). */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
    };
  };
  readonly sendKoraSessionMessage: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        /** @description Opaque board-side session handle. Derived from the registry PK (executor_id, native_id); clients treat it as opaque and stable across listings. Not a harness store id. */
        readonly session_id: components["parameters"]["KoraSessionId"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["KoraMessageCreate"];
      };
    };
    readonly responses: {
      /** @description Accepted into the relay queue. Delivery status is carried in the body — accepted ≠ delivered. */
      readonly 202: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraMessageAcceptedOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
      /** @description Step-up required (code `step_up_required`) or mnd_ wall (code `metadata_only`). */
      readonly 403: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
      /** @description Foreign triple / not steerable — resolved as absent, server-side enforcement (code `session_not_found`). */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
      /** @description Executor host conflict surfaced loudly by the send path (code `host_conflict`) — resolution lives here, never blocks visibility. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
    };
  };
  readonly getKoraSteeringStepUpStatus: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Current step-up state. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraStepUpStatusOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
    };
  };
  readonly enableKoraSteeringStepUp: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["KoraStepUpIn"];
      };
    };
    readonly responses: {
      /** @description Step-up granted. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraStepUpOut"];
        };
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
      /** @description Wrong PIN (code `step_up_denied`); mnd_ cannot step up. */
      readonly 403: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["KoraErrorOut"];
        };
      };
    };
  };
  readonly revokeKoraSteeringStepUp: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Revoked (no body). */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 401: components["responses"]["KoraUnauthorized"];
    };
  };
}
