/**
 * Board-server wire view models for the BoardAdapter (ADR 0011 §6).
 *
 * Entity types that the board OpenAPI names (TaskOut, BoardOut, TaskInboxOut,
 * TaskInboxItem) are re-exported from the generated board OpenAPI types
 * (src/types/board-openapi.d.ts, regenerated by `npm run codegen:board`) —
 * the generated file is the single source of truth. Only shapes the board
 * serves as anonymous `dict[str, Any]` (health, memory item envelope, the
 * mnemos-search proxy) stay hand-written here, mirroring the convention of
 * gateway/types.ts for the mnemos side.
 */
import type { components } from "@/types/board-openapi";

type Schemas = components["schemas"];

// --- Generated entity types (components["schemas"]) -------------------------

/** Board projection — board `BoardOut` schema (`GET /api/board`). */
export type BoardSummary = Schemas["BoardOut"];

/** Board task row — board `TaskOut` schema (SSE `task.*` payloads, board). */
export type BoardTask = Schemas["TaskOut"];

/** AGG-1 inbox payload — board `TaskInboxOut` schema (`GET /api/tasks/inbox`). */
export type TaskInbox = Schemas["TaskInboxOut"];

/** One inbox row — board `TaskInboxItem` schema. */
export type TaskInboxEntry = Schemas["TaskInboxItem"];

/**
 * Merged memory page — board `MemoryListOut` schema (`GET /api/memories`).
 * Cursor contract of ADR 0011 §11; `errors` carries per-store degradation.
 */
export type MergedMemoriesPage = Schemas["MemoryListOut"];

/**
 * One merged-list row — board `MemoryListItem` schema. SEC-4: only an
 * excerpt travels in the list (never full content); `server` disambiguates
 * per-store id collisions.
 */
export type MergedMemoryListItem = Schemas["MemoryListItem"];

/** Aggregated tag listing — board `TagListOut` schema (`GET /api/tags`). */
export type MergedTags = Schemas["TagListOut"];

// --- Ф2 task-domain wire types (generated entity schemas) ---------------------

/** One agent report — board `ReportOut` schema. */
export type TaskReport = Schemas["ReportOut"];

/** Report history — board `ReportsOut` schema (`GET /api/tasks/{id}/reports`). */
export type TaskReports = Schemas["ReportsOut"];

/** One audit event row — board `EventItem` schema (ts + title + detail?). */
export type TaskHistoryEvent = Schemas["EventItem"];

/** One linked-memory row — board `MemoryItem` schema (ts?/source?/detail?). */
export type TaskHistoryMemory = Schemas["MemoryItem"];

/** Merged task timeline — board `HistoryOut` schema (`GET /api/tasks/{id}/history`). */
export type TaskHistory = Schemas["HistoryOut"];

/**
 * Resolved task memory links — board `TaskMemoriesOut` schema
 * (`GET /api/tasks/{id}/memories`). `items` maps a memory id onto an
 * excerpt-only card (SEC-4); `sources` maps the id onto the resolving
 * server; `unresolved` lists links no active server could resolve.
 */
export type TaskMemories = Schemas["TaskMemoriesOut"];

/**
 * Archive page — board `ArchiveOut` schema (`GET /api/archive`). `items` is
 * the limit/offset page; `projects` groups the FULL matching set (stable
 * teaser counts under pagination, BE-11b); `count` is the legacy total key.
 */
export type ArchivePage = Schemas["ArchiveOut"];

/** Archive query params (mirrors the server's filter contract). */
export interface ArchiveParams {
  /** LIKE over title/summary. */
  readonly q?: string;
  /** Exact workflow-status match (`TASK_STATUSES`; empty = all). */
  readonly status?: string;
  /** Exact column match (`VALID_STATUSES`; empty = all). */
  readonly col?: string;
  /** Member-of-agents-array match. */
  readonly agent?: string;
  /** Exact project match. */
  readonly project?: string;
  /** Page size (server clamps to 0..200; default 50). */
  readonly limit?: number;
  /** Page offset (≥ 0). */
  readonly offset?: number;
}

// --- Ф3 mutation wire types (generated entity schemas) -------------------------

/** Create payload — board `TaskCreate` schema (`POST /api/tasks`). */
export type TaskCreateInput = Schemas["TaskCreate"];

/**
 * Content patch — board `TaskPatch` schema (`PATCH /api/tasks/{id}`).
 * `force: true` overrides the BE-12 24h lock (the server echoes forced
 * edits back with `forced: true`); `status` is workflow, never content —
 * the 423 window does not apply to it.
 */
export type TaskPatchInput = Schemas["TaskPatch"];

/** Move payload — board `MoveBody` schema (`POST /api/tasks/{id}/move`). */
export type TaskMoveInput = Schemas["MoveBody"];

/** Archive ack — board `OkOut` schema (`POST /api/tasks/{id}/archive`). */
export type TaskMutationAck = Schemas["OkOut"];

/** Unarchive result — board `UnarchiveOut` schema; `task` may be null. */
export type TaskUnarchiveResult = Schemas["UnarchiveOut"];

/**
 * Inbox scan counters — board `TaskInboxRefreshOut` schema
 * (`POST /api/tasks/inbox/refresh`): `found` rows seen, `new` rows stored.
 */
export type InboxRefreshResult = Schemas["TaskInboxRefreshOut"];


// --- AGW-1 agents-domain wire types (ARCH-9, ADR 0009 Amd 2; SCHED-1) ----------
// Hand-written refinements over the generated schemas where the server
// answers anonymous dicts (routing, executor-list meta) or enum-ish strings;
// entities the OpenAPI already names precisely are re-exported verbatim.
// The full REST projection NEVER carries `claim_token` (secret — it exists
// only inside the claim/finish machine calls) or `spec_snapshot` (immutable
// execution view — only its `spec_hash` fingerprint travels).

/** Assignment lifecycle — the frozen 7-state dictionary (ADR 0009 §4). */
export type AssignmentLifecycleState =
  | "queued"
  | "claimed"
  | "running"
  | "done"
  | "failed"
  | "cancelled"
  | "expired";

/**
 * Routing annotation `{resolved, reason}` — computed per GET over the
 * executor registry (Amd 2 §5: explicit pin → assignment specialist → task
 * specialists → project default → global default → auto best-match →
 * unmatched), stored nowhere. `resolved: null` + reason "unmatched" means
 * the assignment is visible to every poller.
 */
export interface RoutingAnnotation {
  /** Executor id the chain resolves to; null = no route (unmatched). */
  readonly resolved: string | null;
  /** Resolution tier: explicit | specialist | task-specialists | project-default | global-default | auto | unmatched. */
  readonly reason: string;
}

/**
 * One assignment row — board `AssignmentOut` with the anonymous `routing`
 * dict re-typed. `claimed_by` is the DECLARED identity of the claimer —
 * server-unverified, the UI renders it with the unverified affordance.
 */
export interface AssignmentItem {
  readonly id: number;
  readonly task_id: string;
  readonly specialist: string;
  readonly harness: string;
  readonly state: AssignmentLifecycleState;
  /** Who queued the attempt: owner | automation | … (audit actor). */
  readonly created_by: string;
  /** Declared identity of the claimer (unverified, may stay null). */
  readonly claimed_by?: string | null;
  readonly note: string;
  /** Fingerprint of the frozen spec snapshot (the snapshot itself stays server-side). */
  readonly spec_hash: string;
  /** Explicit executor pin — empty string means chain resolution. */
  readonly executor_id: string;
  /** Registry id of the executor that actually claimed (fact, not hint). */
  readonly claimed_by_executor: string;
  readonly created_at: string;
  readonly claimed_at?: string | null;
  readonly started_at?: string | null;
  readonly heartbeat_at?: string | null;
  readonly finished_at?: string | null;
  /** Denormalized project/domain tags (metadata tier). */
  readonly topics: readonly string[];
  readonly routing?: RoutingAnnotation | null;
}

/** Assignment queue page — board `AssignmentsOut` (items re-typed). */
export interface AssignmentsPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly AssignmentItem[];
}

/** Assignment queue filters (`GET /api/assignments`). */
export interface AssignmentListParams {
  /** Exact lifecycle state (dictionary value; empty = all). */
  readonly state?: AssignmentLifecycleState;
  /** Exact task filter. */
  readonly task_id?: string;
  /**
   * Presence piggyback + routing hint, NOT a server-side list filter: an
   * authenticated executor polling with its own id ticks its last_seen
   * clock (ARCH-9). The UI filters by executor client-side.
   */
  readonly executor_id?: string;
}

/** Create payload — board `AssignmentCreate` (`POST /api/assignments`). */
export interface AssignmentCreateInput {
  readonly task_id: string;
  readonly specialist: string;
  /** Harness id (KNOWN_HARNESSES server-side; default "zcode"). */
  readonly harness: string;
  /** Explicit executor pin — omitted/empty means chain resolution. */
  readonly executor_id?: string;
}

/** Create result — board `AssignmentCreatedOut` (assignment re-typed). */
export interface AssignmentCreatedResult {
  readonly ok: boolean;
  readonly assignment: AssignmentItem;
}

/**
 * Cancel result — board `AssignmentFinishedOut` (assignment re-typed).
 * `moved` is `[from, to]` when the task column returned to open, empty
 * otherwise; `report` stays null on cancel (it belongs to done/fail).
 */
export interface AssignmentCancelledResult {
  readonly ok: boolean;
  readonly assignment: AssignmentItem;
  readonly task?: BoardTask | null;
  readonly moved: readonly string[];
  readonly report?: TaskReport | null;
}

/** Executor presence — computed from the last_seen TTL on read, never stored. */
export type ExecutorPresence = "online" | "stale" | "offline";

/** Registry ladder state (Amd 2 §4: machine bootstrap → owner decision). */
export type ExecutorRegistryState = "pending" | "approved" | "revoked";

/** Executor transport (mesh is dispatch-ineligible until R4 lands). */
export type ExecutorTransport = "local-poll" | "mesh-r4";

/**
 * One executor row — board `ExecutorOut` with the enum-ish strings narrowed
 * (presence/state/transport are closed server-side sets). The declared
 * identity (name/host/harness/version) is executor-claimed and
 * server-UNVERIFIED — the UI renders it as such (spec §2.2).
 */
export interface ExecutorItem {
  readonly id: string;
  readonly name: string;
  readonly harness: string;
  readonly host: string;
  readonly transport: ExecutorTransport;
  /** Owner-declared allowlist mappings (specialist roles this executor takes). */
  readonly capabilities: readonly string[];
  readonly version: string;
  /** Routing kill-switch (owner PATCH; disabled executors never resolve). */
  readonly enabled: boolean;
  readonly state: ExecutorRegistryState;
  readonly last_seen: string;
  readonly presence: ExecutorPresence;
  readonly registered_at: string;
  readonly updated_at: string;
}

/**
 * Registry page meta — the server-owned presence contract (spec §5.1): the
 * TTL constants (online ≤ 2 min, stale ≤ 10 min) and the sweeper cadence
 * travel WITH the data; clients read them, never hardcode.
 */
export interface ExecutorListMeta {
  readonly presence: {
    readonly online_max_age_s: number;
    readonly stale_max_age_s: number;
  };
  readonly sweeper_interval_s: number;
}

/** Executor registry page — board `ExecutorListOut` (meta re-typed). */
export interface ExecutorsPage {
  readonly ok: boolean;
  readonly count: number;
  readonly items: readonly ExecutorItem[];
  readonly meta: ExecutorListMeta;
}

/** Execution settings read — board `ExecutionSettingsOut`. */
export type ExecutionSettings = Schemas["ExecutionSettingsOut"];

/**
 * Execution settings write — board `ExecutionSettingsBody` with `scope`
 * optional ('' global by default; 'project:<slug>' reserves per-project
 * defaults, Amd 2 §5). The fallback is the UI's no-silent-substitution
 * preview value; it never joins the GET routing chain.
 */
export interface ExecutionSettingsInput {
  /** Executor id or '' to clear the slot (Amd 2 §5 gates apply server-side). */
  readonly default_executor: string;
  /** Executor id or '' to clear the slot (global scope only). */
  readonly fallback_executor: string;
  readonly scope?: string;
}

// --- SCHED-1 automation wire types (ADR 0013; consumed by a later wave) -------

/** One schedule rule — board `ScheduleOut` schema. */
export type ScheduleRule = Schemas["ScheduleOut"];

/** Schedule create payload — board `ScheduleCreate` schema. */
export type ScheduleCreateInput = Schemas["ScheduleCreate"];

/** Schedule patch payload — board `SchedulePatch` schema (null = absent). */
export type SchedulePatchInput = Schemas["SchedulePatch"];

/** Schedule listing — board `SchedulesOut` schema. */
export type SchedulesPage = Schemas["SchedulesOut"];

/** «Запустить сейчас» result — board `ScheduleRunOut` schema. */
export type ScheduleRunResult = Schemas["ScheduleRunOut"];

/** One hook rule — board `HookOut` schema. */
export type HookRule = Schemas["HookOut"];

/** One condition clause — board `ConditionItem` schema (strict, no free text). */
export type ConditionItem = Schemas["ConditionItem"];

/** Hook create payload — board `HookCreate` schema. */
export type HookCreateInput = Schemas["HookCreate"];

/** Hook patch payload — board `HookPatch` schema (null = absent). */
export type HookPatchInput = Schemas["HookPatch"];

/** Hook listing — board `HooksOut` schema. */
export type HooksPage = Schemas["HooksOut"];

/** Rule DELETE ack — board `RuleDeletedOut` (soft-disable retention note). */
export type RuleDeletedAck = Schemas["RuleDeletedOut"];

/** One launch journal row — board `LaunchOut` schema. */
export type LaunchRow = Schemas["LaunchOut"];

/** Launch journal page — board `LaunchesOut` schema (cursor contract, ADR 0011 §11). */
export type LaunchesPage = Schemas["LaunchesOut"];

/** Engine/caps/condition-meta projection — board `AutomationStatusOut` schema. */
export type AutomationStatus = Schemas["AutomationStatusOut"];

/** Launch journal filters (`GET /api/automation/launches`). */
export interface LaunchesParams {
  readonly rule_id?: number;
  /** schedule | hook (422 on garbage server-side). */
  readonly kind?: string;
  /** launched | skipped | missed. */
  readonly decision?: string;
  /** Page size (server caps at 200; default 50). */
  readonly limit?: number;
  /** Opaque cursor from a previous page's next_cursor. */
  readonly cursor?: string;
}


// --- Anonymous wire shapes (board answers `dict[str, Any]`) ------------------

/**
 * `GET /api/health` payload (anonymous dict on the wire). `servers`/`groups`
 * carry live store state; the adapter projects the scalars onto the viewer's
 * string-map `HealthStatus` and drops the nested arrays.
 */
export interface BoardHealth {
  readonly ok?: boolean;
  readonly service?: string;
  readonly board_tasks?: number;
  readonly servers?: readonly unknown[];
  readonly groups?: readonly unknown[];
}

/**
 * `GET /api/health` — per-store detail (Ф1 Overview «карточки здоровья
 * хранилища»). Captured from the live wire (recorded-corpus rule, QA verdict
 * §5): every server row carries the health-dot contract of ui-contract §7 —
 * `ok` reflects the cheap liveness probe only, never search latency.
 */
export interface BoardHealthServer {
  readonly name: string;
  readonly group_name?: string;
  readonly enabled?: boolean;
  readonly state?: string;
  readonly description?: string | null;
  readonly ok?: boolean;
  readonly latency_ms?: number | null;
  readonly error?: string | null;
  readonly memories_total?: number | null;
}

/** Full board health view the Overview consumes (scalars + store rows). */
export interface BoardHealthDetail {
  readonly ok: boolean;
  readonly service: string;
  readonly board_tasks: number;
  /** Server version (archcom C5 source) — the Sidebar version label; absent
   * on gateways that do not expose it (mock/legacy boards). */
  readonly app_version?: string | null;
  readonly servers: readonly BoardHealthServer[];
}

/**
 * `GET /api/memories/pulse` — merged recency feed (Ф1 Pulse page).
 * Anonymous dict on the wire; shape captured live against the board server
 * (see also server/app.py `memory_pulse_all`). `store_stats` is present ONLY
 * when the merged feed is empty (the server then explains what the stores
 * hold); `per_server` is the honest degradation report — `ok: false` rows
 * carry `detail` and contribute no items.
 */
export interface MemoryPulseItem {
  readonly id: string;
  readonly title: string;
  readonly tags: readonly string[];
  readonly status: string;
  readonly created_at: string;
  /** Provenance: the store that contributed the row (server-assigned). */
  readonly server: string;
}

export interface MemoryPulseServerNote {
  readonly server: string;
  readonly ok: boolean;
  /** How many items this store contributed before the merge cut. */
  readonly items: number;
  /** Failure detail (mnemos error body) — null on the happy path. */
  readonly detail: unknown;
}

export interface MemoryPulse {
  readonly ok: boolean;
  readonly scope: string;
  readonly kind: string;
  readonly items: readonly MemoryPulseItem[];
  readonly per_server: readonly MemoryPulseServerNote[];
  readonly store_stats?: readonly unknown[];
}

/** Pulse query params (`?scope=&project=&limit=`, limit capped at 20 server-side). */
export interface PulseParams {
  /** `'all'` (default), a group name, or one server name; unknown → 404. */
  readonly scope?: string;
  /** Exact project filter (empty = all projects). */
  readonly project?: string;
  readonly limit?: number;
}

/**
 * `GET /api/memories/item/{memory_id}` envelope. `ok: true` carries the
 * reshaped memory card from the first resolving server; `ok: false` is the
 * "not found on any active server" answer.
 */
export type BoardMemoryEnvelope =
  | {
      readonly ok: true;
      readonly server: string;
      readonly memory: {
        readonly id?: string;
        readonly title?: string | null;
        readonly content?: string | null;
        readonly raw_content?: string | null;
        readonly tags?: readonly string[];
        readonly status?: string | null;
        readonly memory_type?: string | null;
        readonly source?: string | null;
        readonly source_url?: string | null;
        readonly project?: string;
        readonly agent?: string;
        readonly created_at?: string | null;
        readonly updated_at?: string | null;
      };
    }
  | {
      readonly ok: false;
      readonly error?: string;
    };

/**
 * `GET /api/mnemos/search` payload (proxied mnemos search). Each hit is an
 * anonymous mnemos search object plus the board-added `server` provenance
 * field; `errors` lists stores whose slice failed.
 */
export interface BoardSearchResponse {
  readonly ok?: boolean;
  readonly results?: readonly unknown[];
  readonly errors?: readonly {
    readonly server?: string;
    readonly status?: number;
    readonly detail?: string | null;
  }[];
}
