/**
 * Board-server wire view models for the BoardAdapter (ADR 0011 §6).
 *
 * Entity types that the board OpenAPI names (TaskOut, BoardOut, TaskInboxOut,
 * TaskInboxItem) are re-exported from the generated board OpenAPI types
 * (src/types/board-openapi.d.ts, regenerated by `npm run codegen:board`) —
 * the generated file is the single source of truth. Only shapes the board
 * serves as anonymous `dict[str, Any]` (health, memory item envelope, the
 * mnemos-search proxy) stay hand-written here, mirroring the convention of
 * gateway/types.ts for the mnemos side.
 */
import type { components } from "@/types/board-openapi";

type Schemas = components["schemas"];

// --- Generated entity types (components["schemas"]) -------------------------

/** Board projection — board `BoardOut` schema (`GET /api/board`). */
export type BoardSummary = Schemas["BoardOut"];

/** Board task row — board `TaskOut` schema (SSE `task.*` payloads, board). */
export type BoardTask = Schemas["TaskOut"];

/** AGG-1 inbox payload — board `TaskInboxOut` schema (`GET /api/tasks/inbox`). */
export type TaskInbox = Schemas["TaskInboxOut"];

/** One inbox row — board `TaskInboxItem` schema. */
export type TaskInboxEntry = Schemas["TaskInboxItem"];

/**
 * Merged memory page — board `MemoryListOut` schema (`GET /api/memories`).
 * Cursor contract of ADR 0011 §11; `errors` carries per-store degradation.
 */
export type MergedMemoriesPage = Schemas["MemoryListOut"];

/**
 * One merged-list row — board `MemoryListItem` schema. SEC-4: only an
 * excerpt travels in the list (never full content); `server` disambiguates
 * per-store id collisions.
 */
export type MergedMemoryListItem = Schemas["MemoryListItem"];

/** Aggregated tag listing — board `TagListOut` schema (`GET /api/tags`). */
export type MergedTags = Schemas["TagListOut"];

// --- Anonymous wire shapes (board answers `dict[str, Any]`) ------------------

/**
 * `GET /api/health` payload (anonymous dict on the wire). `servers`/`groups`
 * carry live store state; the adapter projects the scalars onto the viewer's
 * string-map `HealthStatus` and drops the nested arrays.
 */
export interface BoardHealth {
  readonly ok?: boolean;
  readonly service?: string;
  readonly board_tasks?: number;
  readonly servers?: readonly unknown[];
  readonly groups?: readonly unknown[];
}

/**
 * `GET /api/memories/item/{memory_id}` envelope. `ok: true` carries the
 * reshaped memory card from the first resolving server; `ok: false` is the
 * "not found on any active server" answer.
 */
export type BoardMemoryEnvelope =
  | {
      readonly ok: true;
      readonly server: string;
      readonly memory: {
        readonly id?: string;
        readonly title?: string | null;
        readonly content?: string | null;
        readonly raw_content?: string | null;
        readonly tags?: readonly string[];
        readonly status?: string | null;
        readonly memory_type?: string | null;
        readonly source?: string | null;
        readonly source_url?: string | null;
        readonly project?: string;
        readonly agent?: string;
        readonly created_at?: string | null;
        readonly updated_at?: string | null;
      };
    }
  | {
      readonly ok: false;
      readonly error?: string;
    };

/**
 * `GET /api/mnemos/search` payload (proxied mnemos search). Each hit is an
 * anonymous mnemos search object plus the board-added `server` provenance
 * field; `errors` lists stores whose slice failed.
 */
export interface BoardSearchResponse {
  readonly ok?: boolean;
  readonly results?: readonly unknown[];
  readonly errors?: readonly {
    readonly server?: string;
    readonly status?: number;
    readonly detail?: string | null;
  }[];
}
