/**
 * Board-server wire view models for the BoardAdapter (ADR 0011 §6).
 *
 * Entity types that the board OpenAPI names (TaskOut, BoardOut, TaskInboxOut,
 * TaskInboxItem) are re-exported from the generated board OpenAPI types
 * (src/types/board-openapi.d.ts, regenerated by `npm run codegen:board`) —
 * the generated file is the single source of truth. Only shapes the board
 * serves as anonymous `dict[str, Any]` (health, memory item envelope, the
 * mnemos-search proxy) stay hand-written here, mirroring the convention of
 * gateway/types.ts for the mnemos side.
 */
import type { components } from "@/types/board-openapi";

type Schemas = components["schemas"];

// --- Generated entity types (components["schemas"]) -------------------------

/** Board projection — board `BoardOut` schema (`GET /api/board`). */
export type BoardSummary = Schemas["BoardOut"];

/** Board task row — board `TaskOut` schema (SSE `task.*` payloads, board). */
export type BoardTask = Schemas["TaskOut"];

/** AGG-1 inbox payload — board `TaskInboxOut` schema (`GET /api/tasks/inbox`). */
export type TaskInbox = Schemas["TaskInboxOut"];

/** One inbox row — board `TaskInboxItem` schema. */
export type TaskInboxEntry = Schemas["TaskInboxItem"];

/**
 * Merged memory page — board `MemoryListOut` schema (`GET /api/memories`).
 * Cursor contract of ADR 0011 §11; `errors` carries per-store degradation.
 */
export type MergedMemoriesPage = Schemas["MemoryListOut"];

/**
 * One merged-list row — board `MemoryListItem` schema. SEC-4: only an
 * excerpt travels in the list (never full content); `server` disambiguates
 * per-store id collisions.
 */
export type MergedMemoryListItem = Schemas["MemoryListItem"];

/** Aggregated tag listing — board `TagListOut` schema (`GET /api/tags`). */
export type MergedTags = Schemas["TagListOut"];

// --- Ф2 task-domain wire types (generated entity schemas) ---------------------

/** One agent report — board `ReportOut` schema. */
export type TaskReport = Schemas["ReportOut"];

/** Report history — board `ReportsOut` schema (`GET /api/tasks/{id}/reports`). */
export type TaskReports = Schemas["ReportsOut"];

/** One audit event row — board `EventItem` schema (ts + title + detail?). */
export type TaskHistoryEvent = Schemas["EventItem"];

/** One linked-memory row — board `MemoryItem` schema (ts?/source?/detail?). */
export type TaskHistoryMemory = Schemas["MemoryItem"];

/** Merged task timeline — board `HistoryOut` schema (`GET /api/tasks/{id}/history`). */
export type TaskHistory = Schemas["HistoryOut"];

/**
 * Resolved task memory links — board `TaskMemoriesOut` schema
 * (`GET /api/tasks/{id}/memories`). `items` maps a memory id onto an
 * excerpt-only card (SEC-4); `sources` maps the id onto the resolving
 * server; `unresolved` lists links no active server could resolve.
 */
export type TaskMemories = Schemas["TaskMemoriesOut"];

/**
 * Archive page — board `ArchiveOut` schema (`GET /api/archive`). `items` is
 * the limit/offset page; `projects` groups the FULL matching set (stable
 * teaser counts under pagination, BE-11b); `count` is the legacy total key.
 */
export type ArchivePage = Schemas["ArchiveOut"];

/** Archive query params (mirrors the server's filter contract). */
export interface ArchiveParams {
  /** LIKE over title/summary. */
  readonly q?: string;
  /** Exact workflow-status match (`TASK_STATUSES`; empty = all). */
  readonly status?: string;
  /** Exact column match (`VALID_STATUSES`; empty = all). */
  readonly col?: string;
  /** Member-of-agents-array match. */
  readonly agent?: string;
  /** Exact project match. */
  readonly project?: string;
  /** Page size (server clamps to 0..200; default 50). */
  readonly limit?: number;
  /** Page offset (≥ 0). */
  readonly offset?: number;
}

// --- Anonymous wire shapes (board answers `dict[str, Any]`) ------------------

/**
 * `GET /api/health` payload (anonymous dict on the wire). `servers`/`groups`
 * carry live store state; the adapter projects the scalars onto the viewer's
 * string-map `HealthStatus` and drops the nested arrays.
 */
export interface BoardHealth {
  readonly ok?: boolean;
  readonly service?: string;
  readonly board_tasks?: number;
  readonly servers?: readonly unknown[];
  readonly groups?: readonly unknown[];
}

/**
 * `GET /api/health` — per-store detail (Ф1 Overview «карточки здоровья
 * хранилища»). Captured from the live wire (recorded-corpus rule, QA verdict
 * §5): every server row carries the health-dot contract of ui-contract §7 —
 * `ok` reflects the cheap liveness probe only, never search latency.
 */
export interface BoardHealthServer {
  readonly name: string;
  readonly group_name?: string;
  readonly enabled?: boolean;
  readonly state?: string;
  readonly description?: string | null;
  readonly ok?: boolean;
  readonly latency_ms?: number | null;
  readonly error?: string | null;
  readonly memories_total?: number | null;
}

/** Full board health view the Overview consumes (scalars + store rows). */
export interface BoardHealthDetail {
  readonly ok: boolean;
  readonly service: string;
  readonly board_tasks: number;
  readonly servers: readonly BoardHealthServer[];
}

/**
 * `GET /api/memories/pulse` — merged recency feed (Ф1 Pulse page).
 * Anonymous dict on the wire; shape captured live against the board server
 * (see also server/app.py `memory_pulse_all`). `store_stats` is present ONLY
 * when the merged feed is empty (the server then explains what the stores
 * hold); `per_server` is the honest degradation report — `ok: false` rows
 * carry `detail` and contribute no items.
 */
export interface MemoryPulseItem {
  readonly id: string;
  readonly title: string;
  readonly tags: readonly string[];
  readonly status: string;
  readonly created_at: string;
  /** Provenance: the store that contributed the row (server-assigned). */
  readonly server: string;
}

export interface MemoryPulseServerNote {
  readonly server: string;
  readonly ok: boolean;
  /** How many items this store contributed before the merge cut. */
  readonly items: number;
  /** Failure detail (mnemos error body) — null on the happy path. */
  readonly detail: unknown;
}

export interface MemoryPulse {
  readonly ok: boolean;
  readonly scope: string;
  readonly kind: string;
  readonly items: readonly MemoryPulseItem[];
  readonly per_server: readonly MemoryPulseServerNote[];
  readonly store_stats?: readonly unknown[];
}

/** Pulse query params (`?scope=&project=&limit=`, limit capped at 20 server-side). */
export interface PulseParams {
  /** `'all'` (default), a group name, or one server name; unknown → 404. */
  readonly scope?: string;
  /** Exact project filter (empty = all projects). */
  readonly project?: string;
  readonly limit?: number;
}

/**
 * `GET /api/memories/item/{memory_id}` envelope. `ok: true` carries the
 * reshaped memory card from the first resolving server; `ok: false` is the
 * "not found on any active server" answer.
 */
export type BoardMemoryEnvelope =
  | {
      readonly ok: true;
      readonly server: string;
      readonly memory: {
        readonly id?: string;
        readonly title?: string | null;
        readonly content?: string | null;
        readonly raw_content?: string | null;
        readonly tags?: readonly string[];
        readonly status?: string | null;
        readonly memory_type?: string | null;
        readonly source?: string | null;
        readonly source_url?: string | null;
        readonly project?: string;
        readonly agent?: string;
        readonly created_at?: string | null;
        readonly updated_at?: string | null;
      };
    }
  | {
      readonly ok: false;
      readonly error?: string;
    };

/**
 * `GET /api/mnemos/search` payload (proxied mnemos search). Each hit is an
 * anonymous mnemos search object plus the board-added `server` provenance
 * field; `errors` lists stores whose slice failed.
 */
export interface BoardSearchResponse {
  readonly ok?: boolean;
  readonly results?: readonly unknown[];
  readonly errors?: readonly {
    readonly server?: string;
    readonly status?: number;
    readonly detail?: string | null;
  }[];
}
