import { afterEach, describe, expect, it, vi } from "vitest";
import { renderToString } from "react-dom/server";
import { MemoryRouter } from "react-router";

import { DOC_CATEGORIES, docCategory } from "./categories";
import {
  getManifest,
  localeForPage,
  parseFrontmatter,
  stripLeadingH1,
  titleFor,
} from "./manifest";
import { docModuleEntries, loadMarkdown, parseDocPath } from "./markdownModules";
import { loadSidecar } from "./sidecar";
import { projectOfDocSlug } from "./projects";
import { Markdown } from "./Markdown";

/**
 * Manifest integrity + corpus gates (contract §6/§9.3): every content file
 * has a valid frontmatter (required fields, existing category, slug = file
 * name, unique order per category), the SIDECAR and the corpus agree both
 * ways (W1c gate), every contract category is non-empty, and the whole
 * corpus renders through Markdown.tsx without a single console error/warning.
 */

const errorSpy = vi.spyOn(console, "error");
const warnSpy = vi.spyOn(console, "warn");

afterEach(() => {
  errorSpy.mockClear();
  warnSpy.mockClear();
});

/** Our pages pin a release (`1.16.0`); imported pages pin a date. */
const VERSION_OR_DATE = /^(\d+\.\d+\.\d+|\d{4}-\d{2}-\d{2})$/;

describe("frontmatter integrity", () => {
  it("parses every content file into slug + locale (flat + upstream layouts)", () => {
    const entries = docModuleEntries();
    // Our 15 + the imported corpus (34 files / 19 slugs) — contract §3/§4.
    expect(entries.length).toBeGreaterThanOrEqual(45);
    for (const [path] of entries) {
      expect(parseDocPath(path), path).not.toBeNull();
    }
  });

  it("names imported slugs <project>/<path> and keeps ours single-segment", () => {
    for (const [path] of docModuleEntries()) {
      const parsed = parseDocPath(path)!;
      if (parsed.project !== undefined) {
        expect(parsed.slug, path).toMatch(new RegExp(`^${parsed.project}/.+`));
        expect(projectOfDocSlug(parsed.slug), path).toBe(parsed.project);
      } else {
        expect(parsed.slug, path).not.toContain("/");
        expect(projectOfDocSlug(parsed.slug), path).toBe("vesmaro-eyes");
      }
    }
  });

  // ME-006: the whole-corpus loops legitimately take seconds of CPU; under
  // a loaded CI runner the default 5s budget killed them mid-loop. The
  // budget is wall-clock only — every assertion below is unchanged.
  it("gives every file the required fields with slug = file name", { timeout: 20_000 }, async () => {
    for (const [path, load] of docModuleEntries()) {
      const raw = await load();
      const parsed = parseFrontmatter(raw);
      if (parsed === null) throw new Error(`${path}: malformed frontmatter`);
      const { fields } = parsed;
      for (const key of ["title", "slug", "category", "order", "last_verified"]) {
        expect(fields[key], `${path}: ${key}`).toBeTruthy();
      }
      const parsedPath = parseDocPath(path)!;
      expect(fields.slug, path).toBe(parsedPath.slug);
      expect(fields.order, path).toMatch(/^\d+$/);
      expect(fields.last_verified, path).toMatch(VERSION_OR_DATE);
      expect(docCategory(fields.category), `${path}: category`).not.toBeNull();
    }
  });

  it("keeps order unique within a category and every category non-empty", async () => {
    const { pages } = await getManifest();
    for (const category of DOC_CATEGORIES) {
      const inCategory = pages.filter((page) => page.category === category.slug);
      expect(inCategory.length, `category ${category.slug} is empty`).toBeGreaterThan(
        0,
      );
      const orders = inCategory.map((page) => page.order);
      expect(new Set(orders).size, category.slug).toBe(orders.length);
      // A category lives in exactly ONE project hub (contract §4).
      const projects = new Set(inCategory.map((page) => page.project));
      expect([...projects], category.slug).toEqual([category.project]);
    }
  });

  it("reports invalid frontmatter and EXCLUDES the page (no crash)", () => {
    expect(parseFrontmatter("no frontmatter at all")).toBeNull();
    expect(parseFrontmatter("---\nonly-key\n---\nbody")).toBeNull(); // not key: value
    expect(parseFrontmatter("---\ntitle: x\n---\nbody")).not.toBeNull();
  });

  it("strips the leading body h1 (the page renders its own from frontmatter)", () => {
    expect(stripLeadingH1("# Title\n\ntext")).toBe("text");
    expect(stripLeadingH1("text")).toBe("text");
  });

  it("strips the imported h1 AFTER the curator preamble, fence-aware", () => {
    const imported = [
      "<!-- GENERATED by sync_docs -->",
      "",
      "> Куратор: первый прогон.",
      "",
      "# Начало работы",
      "",
      "Тело страницы.",
      "",
      "```bash",
      "# это комментарий кода, не заголовок",
      "pip install mnemos",
      "```",
    ].join("\n");
    const stripped = stripLeadingH1(imported);
    expect(stripped).not.toContain("# Начало работы");
    expect(stripped).toContain("Куратор: первый прогон.");
    expect(stripped).toContain("# это комментарий кода, не заголовок");
    expect(stripped).toContain("pip install mnemos");
  });

  it("falls titles back to the ORIGINAL locale, not blindly ru (spec §7.1)", async () => {
    const { pages } = await getManifest();
    for (const page of pages) {
      expect(titleFor(page, "ru"), page.slug).not.toBe("");
      if (!page.locales.includes("en")) {
        // An en-UI reader gets the original-language title.
        expect(titleFor(page, "en"), page.slug).toBe(titleFor(page, "ru"));
      }
      // The effective locale never promises a file that does not exist.
      for (const lang of ["ru", "en"] as const) {
        expect(page.locales, page.slug).toContain(localeForPage(page, lang));
      }
    }
  });
});

describe("sidecar ↔ corpus integrity (W1c gate, contract §6.5)", () => {
  it("resolves every sidecar slug to a real file per declared locale", async () => {
    const sidecar = await loadSidecar();
    expect(sidecar).not.toBeNull();
    expect(sidecar!.pages.length).toBeGreaterThan(0);
    for (const entry of sidecar!.pages) {
      expect(entry.locales.length, entry.slug).toBeGreaterThan(0);
      for (const locale of entry.locales) {
        const raw = await loadMarkdown(entry.slug, locale);
        expect(raw, `${entry.slug}[${locale}]`).toBeDefined();
        const frontmatter = parseFrontmatter(raw!);
        expect(frontmatter, `${entry.slug}[${locale}]`).not.toBeNull();
        // The generated frontmatter must agree with the generated sidecar.
        expect(frontmatter!.fields.slug, entry.slug).toBe(entry.slug);
        expect(frontmatter!.fields.title, entry.slug).toBe(entry.titles[locale]);
      }
      // Gate §6.5: full provenance for every imported page.
      expect(entry.provenance?.repo, entry.slug).toBeTruthy();
      expect(entry.provenance?.source_path, entry.slug).toBeTruthy();
      expect(entry.provenance?.sha, entry.slug).toMatch(/^[0-9a-f]{40}$/);
      expect(entry.provenance?.commit_date, entry.slug).toMatch(/^\d{4}-\d{2}-\d{2}/);
    }
  });

  it("puts every upstream file IN the sidecar (no orphans, both ways)", async () => {
    const sidecar = await loadSidecar();
    const sidecarKeys = new Set(
      (sidecar?.pages ?? []).flatMap((entry) =>
        entry.locales.map((locale) => `${entry.slug}#${locale}`),
      ),
    );
    const moduleKeys = new Set<string>();
    for (const [path] of docModuleEntries()) {
      const parsed = parseDocPath(path);
      if (parsed === null || parsed.project === undefined) continue;
      moduleKeys.add(`${parsed.slug}#${parsed.locale}`);
    }
    expect(moduleKeys.size, "sanity: upstream files exist").toBeGreaterThan(0);
    expect(
      [...moduleKeys].filter((key) => !sidecarKeys.has(key)),
      "upstream files missing from the sidecar",
    ).toEqual([]);
    expect(
      [...sidecarKeys].filter((key) => !moduleKeys.has(key)),
      "sidecar entries with no file behind them",
    ).toEqual([]);
  });
});

describe("corpus render (contract §9.3)", () => {
  it("renders every page without console errors or warnings", { timeout: 20_000 }, async () => {
    const { pages } = await getManifest();
    // One manifest page per our file + per upstream SLUG (not per file —
    // the two locales of an upstream page are one page).
    const fileCount = docModuleEntries().length;
    expect(pages.length).toBeLessThanOrEqual(fileCount);
    expect(pages.length).toBeGreaterThanOrEqual(30);
    for (const page of pages) {
      const raw = await loadMarkdown(page.slug, localeForPage(page, "ru"));
      expect(raw, page.slug).toBeDefined();
      const body = stripLeadingH1(parseFrontmatter(raw!)!.body);
      const html = renderToString(
        <MemoryRouter>
          <Markdown source={body} pageSlug={page.slug} />
        </MemoryRouter>,
      );
      expect(html.length, page.slug).toBeGreaterThan(100);
      // One h1 per page comes from frontmatter, not the body.
      expect((html.match(/<h1/g) ?? []).length, page.slug).toBe(0);
    }
    expect(unexpectedErrors(), JSON.stringify(unexpectedErrors())).toEqual([]);
    expect(unexpectedWarnings()).toEqual([]);
  });
});

/** console noise that is environment, not content: MemoryRouter's SSR note. */
const RENDER_ENV_NOISE = /useLayoutEffect does nothing on the server/;

function unexpectedErrors(): unknown[][] {
  return errorSpy.mock.calls.filter((call) => !RENDER_ENV_NOISE.test(String(call[0])));
}

function unexpectedWarnings(): unknown[][] {
  return warnSpy.mock.calls.filter((call) => !RENDER_ENV_NOISE.test(String(call[0])));
}


describe("firstParagraph banner hygiene (АРХКОМ-8 follow-up)", () => {
  it("skips leading GENERATED/curated comment banners", async () => {
    const { firstParagraph } = await import("./manifest");
    const body = [
      "<!-- GENERATED by sync_docs from mnemos@23f0fce — правки через sync-config.yaml overlay -->",
      "",
      "Слой интеграции Mnemos — это набор поведенческих триггеров.",
    ].join("\n");
    expect(firstParagraph(body)).toBe(
      "Слой интеграции Mnemos — это набор поведенческих триггеров.",
    );
  });

  it("keeps a comment embedded inside a content paragraph (not a banner)", async () => {
    const { firstParagraph } = await import("./manifest");
    const body = "Абзац с комментарием <!-- внутри --> продолжается дальше.";
    expect(firstParagraph(body)).toContain("Абзац с комментарием");
  });
});
