/**
 * Auto-generated from the mnemos OpenAPI schema (`/openapi.json`) via
 * `openapi-typescript`. **DO NOT EDIT — generated file.**
 *
 * Regenerate with: `npm run codegen` (viewer/scripts/codegen.sh).
 * CI regenerates and fails on drift (architecture.md §8).
 *
 * ---------------------------------------------------------------------------
 * PLACEHOLDER (task T1 scaffold): the real schema types are generated by
 * task T3 once wired to the live mnemos instance. The empty shapes below keep
 * `typecheck` green in the meantime and mirror openapi-typescript's export
 * surface so T3's output is a drop-in replacement.
 * ---------------------------------------------------------------------------
 */

export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: Record<string, never>;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type operations = Record<string, never>;

export type external = Record<string, never>;
